apiVersion: v1
kind: Secret
metadata:
  name: fileprocessing-secrets
  namespace: fileprocessing
type: Opaque
stringData:
  postgres-user: "admin"
  postgres-password: "password"
  rabbitmq-user: "guest"
  rabbitmq-password: "guest"
  rabbitmq-url: amqp://guest:guest@rabbitmq-service.fileprocessing.svc.cluster.local:5672/
  minio-access-key: "miniouser"
  minio-secret-key: "miniopass"