apiVersion: v1
kind: ConfigMap
metadata:
  name: ${PROJECT_NAME}-config
  namespace: ${PROJECT_NAME}
data:
  DATABASE_URL: postgresql://admin:password@postgres-service:5432/fileprocessing
  RABBITMQ_URL: amqp://guest:guest@rabbitmq-service:5672/
  S3_ENDPOINT: http://minio-service:9000
  RABBITMQ_HOST: rabbitmq-service
  RABBITMQ_PORT: "5672"
  NFS_MOUNT_PATH: /nfs_data