apiVersion: v1
kind: ConfigMap
metadata:
  name: ${PROJECT_NAME}-config
  namespace: ${PROJECT_NAME}
data:
  postgres-host: "postgres-service"
  postgres-db: "${PROJECT_NAME}"
  rabbitmq-host: "rabbitmq-service"
  minio-host: "minio-service:9000"
  storage-path: "/data/files"
  notification-service-url: "http://notifier-service"
  api-url: "http://api-service"
  s3-endpoint: "http://minio-service:9000"