apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileprocessing-ingress
  namespace: ${PROJECT_NAME}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: fileprocessing.example.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 8000
      - path: /minio
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9001