apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: ${PROJECT_NAME}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 100.80.77.189
    path: "/srv/nfs/share"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: ${PROJECT_NAME}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi