apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: ${PROJECT_NAME}
  labels:
    app: notifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: ${DOCKER_REGISTRY}/${PROJECT_NAME}-notifier:${TAG}
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: ${PROJECT_NAME}-config
              key: postgres-host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ${PROJECT_NAME}-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ${PROJECT_NAME}-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${PROJECT_NAME}-secrets
              key: postgres-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: ${PROJECT_NAME}-config
              key: rabbitmq-host
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: ${PROJECT_NAME}-secrets
              key: rabbitmq-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${PROJECT_NAME}-secrets
              key: rabbitmq-password
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
spec:
  selector:
    app: notifier
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP