apiVersion: v1
kind: Secret
metadata:
  name: ${PROJECT_NAME}-secret
  namespace: ${PROJECT_NAME}
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  S3_ACCESS_KEY: miniouser
  S3_SECRET_KEY: miniopass