apiVersion: v1
kind: Secret
metadata:
  name: ${PROJECT_NAME}-secrets
  namespace: ${PROJECT_NAME}
type: Opaque
stringData:
  postgres-user: "admin"
  postgres-password: "password"
  rabbitmq-user: "guest"
  rabbitmq-password: "guest"
  rabbitmq-url: amqp://guest:guest@rabbitmq-service.${PROJECT_NAME}.svc.cluster.local:5672/
  minio-access-key: "miniouser"
  minio-secret-key: "miniopass"